export const ActivityActions = {
  CREATED: 'CREATED',
  UPDATED: 'UPDATED',
  DELETED: 'DELETED',
  MASTER_WALLET_CREDITED: 'MASTER_WALLET_CREDITED',
  MASTER_WALLET_DEBITED: 'MASTER_WALLET_DEBITED',
  MEMBER_WALLET_CREDITED: 'MEMBER_WALLET_CREDITED',
  MEMBER_WALLET_DEBITED: 'MEMBER_WALLET_DEBITED',
  MEMBER_PAYOUT_CREATED: 'MEMBER_PAYOUT_CREATED',
  EXPENSE_CREATED: 'EXPENSE_CREATED',
} as const;

export const TrackableTypes = {
  MASTER_WALLETS: 'MASTER_WALLETS',
  MEMBER_WALLETS: 'MEMBER_WALLETS',
  EXPENSE_CATEGORIES: 'EXPENSE_CATEGORIES',
  TRANSACTIONS: 'TRANSACTIONS',
} as const;